### ISSUE TITLE
npm install the wrong package

### ISSUE THREAD

**Issue by geekyme** [mridgway/react-server#2]
Hello, 

when i did an npm install, it is pulling from the wrong package.. 

`react-server@0.0.1 node_modules/react-server`

That does not seem right since this package is 1.0.2

**Comment by Vijar** [comment]
@geekyme someone else took the [`react-server`](https://www.npmjs.com/package/react-server) npm package name. This isn't the same package.

**Comment by mridgway** [comment]
Yeah, I do not have plans of releasing this on npm. It is purely a hacking ground for testing changes that could be made in React core. Each of the changes that I have found helpful will be made into PRs/issues (or have already: https://github.com/facebook/react/pull/3922, https://github.com/facebook/react/issues/2895, https://github.com/facebook/react/pull/3665, https://github.com/facebook/react/issues/4012)

**Comment by geekyme** [comment]
thx for clarifying!
